### ISSUE TITLE
Can access to device only as root

### ISSUE THREAD

**Issue by mmzarzu** [ktossell/libuvc#22]
Hi,

I can only launch the examples using sudo. 
How could I access the device avoiding this?

Best

**Comment by mkassner** [comment]
have a look at this: #20

**Comment by ktossell** [comment]
Hey @mkassner, sorry about the silence. There's more information at http://wiki.ros.org/libuvc_camera#Permissions .

**Comment by mmzarzu** [comment]
Thanks!
