### ISSUE TITLE
Question: Force bulk transfer

### ISSUE THREAD

**Issue by mkassner** [ktossell/libuvc#23]
Hi,
Some cameras have alt settings with tremendously oversized packet sizes and I would like to not use iso transfers in this case.

Is is possible to force bulk transfer?
(I tried forcing bulk transfers in stream.c but  libusb_submit_transfer fails with 'Entity not found.' .)

Any pointers would be very appreciated.

**Comment by ktossell** [comment]
I believe that UVC camera streaming interfaces can do isochronous transfers or bulk transfers, but not both. The camera would have to provide more than one streaming interface for that to be possible.

I think the approach you're taking in https://github.com/pupil-labs/libuvc/commits/bandwidth_fix is the best way to go.

**Comment by mkassner** [comment]
Alright that makes sense. Closed
