### ISSUE TITLE
Compilation with Visual Studio 2015 Community

### ISSUE THREAD

**Issue by nosleduc** [ktossell/libuvc#45]
I'm trying to compile libuvc with vs 2015 but it fails because of the pthread.h.
How can I compile libuvc with vs 2015 ?

**Comment by Rhodanos** [comment]
Build pthread for windows found at "https://github.com/GerHobbelt/pthread-win32.git" and include it in the CMakeLists.txt of Libuvc

**Comment by Rhodanos** [comment]
You can also do the following:
replace 

`#include <pthread.h>` in libuvc_internal.h

with 

`#ifdef _WIN32
#include "winpthreads.h"
#else
#include <pthread.h>
#endif`

After doing so, you must comment out the timespec struct in winpthreads.h, since windows has it shipped in later sdk versions.

**Comment by nosleduc** [comment]
Thanks
